### ISSUE TITLE
Hunk #1 FAILED at 40. 

### ISSUE THREAD

**Issue by ghost** [andybalaam/retropie-recording#2]
Trying to run the build-retroarch-with-ffmpeg.sh and getting the error below. 

patching file scriptmodules/emulators/retroarch.sh
Hunk #1 FAILED at 40.
1 out of 1 hunk FAILED -- saving rejects to file scriptmodules/emulators/retroarch.sh.rej

Below is the contents of the patch file. The output as you probably already guessed to retroarch.sh.rej is also the same. 

diff --git a/scriptmodules/emulators/retroarch.sh b/scriptmodules/emulators/retroarch.sh
index 2a28bf4..e1c14a4 100644
--- a/scriptmodules/emulators/retroarch.sh
+++ b/scriptmodules/emulators/retroarch.sh
@@ -40,7 +40,7 @@ function sources_retroarch() {

 function build_retroarch() {
     local params=(--disable-sdl --enable-sdl2 --disable-oss --disable-al --disable-jack)
-    ! isPlatform "x11" && params+=(--disable-x11 --disable-ffmpeg --disable-pulse)
+    ! isPlatform "x11" && params+=(--disable-x11 --disable-pulse)
     isPlatform "gles" && params+=(--enable-opengles)
     isPlatform "rpi" && params+=(--enable-dispmanx)
     isPlatform "mali" && params+=(--enable-mali_fbdev)

**Comment by andybalaam** [comment]
Yes, I think the patch has got out-of-date.  Pull requests happily accepted - I may get around to fixing this sometime, but it's not going to be soon, sorry :-(

**Comment by andybalaam** [comment]
Closing since I'm not working on it, but merge requests happily accepted.
