### ISSUE TITLE
Copy the blog post on Github ?

### ISSUE THREAD

**Issue by cosmo0** [andybalaam/retropie-recording#4]
Your blog post is out of date with the current version of RetroPie/RetroArch. How about copying it on Github so it can have pull requests ?

- I personnaly think it's easier to install Pixel Desktop (in experimental packages) to manipulate RetroPie directly from within RetroPie, it's pretty powerful (especially when using a Pi 400)
- Recompiling RetroArch is not necessary anymore (and the patch doesn't work)
- You can also launch recording from within a game (hotkey + X, start recording), in this case you have to configure RetroArch to load the config file (a few configuration steps are necessary)

Thanks for the post though, I was able to set up recording (even though it doesn't record shaders and overlays... :/)

**Comment by andybalaam** [comment]
Excellent idea.  Please do contribute MRs for the problems you mentioned, including explaining (as an alternative) how to use Pixel Desktop if you like.

**Comment by andybalaam** [comment]
For reference, the copy of the blog post is now here: https://github.com/andybalaam/retropie-recording/blob/master/instructions.md
